name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install libguestfs-tools
        run: sudo apt-get install libguestfs-tools

      - name: Build ubuntu 20.04 rpi4 image with cloud-init config
        run: ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-20.04.1-lava-worker-arm64+raspi.img.xz
          path: out/*.img.xz
          if-no-files-found: error